name: "yeah boi"
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "*/60 * * * *"

jobs:
  Yamete_kudasai:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
          

      - name: run me uwu
        run: curl -I -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36" "https://flixhq.to/"  > domain.txt
        
      - name: auwuto commit uwu
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "update: status"
          repository: .
          file_pattern: 'domain.txt'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
