name: "yeah boi"
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "*/60 * * * *"

jobs:
  Yamete_kudasai:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
          

      - name: run me uwu
        run: curl -I "https://yugenanime.tv/" | head -n1 | cut -d' ' -f2 > domain.txt
        
      - name: auwuto commit uwu
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "update: status"
          repository: .
          file_pattern: 'domain.txt'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
